#!/bin/bash
#SBATCH --job-name=mutatex-analysis
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=2:00:00
#SBATCH --output=build1.stdout
#SBATCH --error=build1.stderr

# eventually load other modules
#module purge
#module load Package1 Package2 Package3

# go to the (current) working directory (optional, if this is the
# directory where you submitted the job)

echo Start Job
date

#ddg2heatmap -p $PDB -d $RESULTS  -l $MUTLIST -s 50 -F Arial -n -3 -x 5 -c plasma -b labels_1D5R_clean_shorter.csv
#ddg2distribution -p $PDB -l $MUTLIST -d $RESULTS -T box -F Arial -s 50 -n -3 -x 22 -b labels_1D5R_clean_shorter.csv

#export PDB=../1D5R_noheatm.pdb

#ddg2distribution -p $PDB -l $MUTLIST -d $RESULTS -T average -F Arial -s 500 -n -3 -x 22 -c viridis -u 10 -b labels_1D5R_clean.csv

APPTAINER_CACHEDIR=/tmp/ \
APPTAINER_TMPDIR=/tmp/ \
apptainer exec $VSC_SCRATCH/mutatex-v1.sif /opt/conda/envs/mutatex/bin/ddg2heatmap \
        -p ../../model_on_1jxx1A_model0_checked.pdb \
        -l ../../mutation_list.txt \
        -d ../../results/mutation_ddgs/model_on_1jxx1A_model0_checked_Repair/\
        -s 50 \
        -n -3 -x 5 \
	-c plasma \
        -b labels_1jxx1A.csv &> analysis.log

date
echo End Job
